name: IOMe Web

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Change to the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Selenium tests
      run: |
        # Start the Xvfb virtual framebuffer
        sudo apt-get install -y xvfb
        Xvfb :99 -ac &
        export DISPLAY=:99
        
      
        pytest iome_web.py   
