name: IOMe Web
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    
    services:
      chrome:
        image: sselvagg/chrome-headless
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g
          --no-sandbox
          --disable-dev-shm-usage
          
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest selenium

    - name: Run Selenium Tests
      env:
        URL: 'https://iome.ai'  # Specify your URL here
      run: |
          pytest iome/iome_web.py  # Update with the path to your test file
