name: Python Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    services:
      # Service for running a Selenium Chrome instance using the Selenium Standalone Chrome container
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --health-cmd "curl -sSL http://localhost:4444/wd/hub/status || exit 1"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 5

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-selenium

    # Step 4: Run Selenium WebDriver Tests
    - name: Run Selenium Tests with pytest
      env:
        DISPLAY: ":99"
      run: |
        pytest sarva/sarva-web.py
